spring:
  mail: 
    host: smtp.gmail.com
    port: 587
    properties:
        mail:
            smtp:              
                auth: true
                starttls:
                    required: true
                    enable: true    
    username: grupo2egg@gmail.com
    password: bheqdtwkwmlanxzw               
  mvc:
    format:
      date: yyyy-MM-dd

  datasource: 
    url: jdbc:mysql://localhost:3306/calificar?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa: 
    show-sql: false
    hibernate:
      ddl-auto: update 
  thymeleaf:
    cache: false 
server:
  port: 8080
  

